/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ControleDeFrequencia.View;

import br.com.ControleDeFrequencia.Control.ControlDisciplina;
import br.com.ControleDeFrequencia.Control.ControlProfessor;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class JanCad_Disciplina extends javax.swing.JDialog implements ADMJanelas{
    
    private ArrayList<String[]> professores;
    private HashMap<String, String> infoJanela;
    /**
     * Creates new form JanCad_Cadeira
     */
    public JanCad_Disciplina() {
        this.setModal(true);
        initComponents();
        this.preencherListaProfessores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nivelGroup = new javax.swing.ButtonGroup();
        jTFCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFDisciplina = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCBSemestre = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTFCargaHoraria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCBProfessor = new javax.swing.JComboBox();
        jTFCodigoProfessor = new javax.swing.JTextField();
        jBtnSalvar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRBMedio = new javax.swing.JRadioButton();
        jRBSuperior = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jCBSerie = new javax.swing.JComboBox();
        jCBCurso = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        nivelGroup.add(jRBMedio);
        nivelGroup.add(jRBSuperior);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Disciplinas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFCodigo.setEnabled(false);
        getContentPane().add(jTFCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, 83, -1));

        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));
        getContentPane().add(jTFDisciplina, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 29, 300, -1));

        jLabel2.setText("Disciplina");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 11, -1, -1));

        jCBSemestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "1º Semestre", "2º Semestre", "3º Semestre", "4º Semestre", "5º Semestre", "6º Semestre", "7º Semestre", "8º Semestre", "9º Semestre", "10º Semestre" }));
        jCBSemestre.setEnabled(false);
        getContentPane().add(jCBSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 122, -1));

        jLabel3.setText("Semestre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));
        getContentPane().add(jTFCargaHoraria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 130, -1));

        jLabel4.setText("Carga Horária");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Professor"));

        jCBProfessor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBProfessorItemStateChanged(evt);
            }
        });

        jTFCodigoProfessor.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTFCodigoProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCodigoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 389, -1));

        jBtnSalvar.setText("Salvar");
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 75, -1));

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nível"));

        jRBMedio.setText("Médio");
        jRBMedio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRBMedioStateChanged(evt);
            }
        });

        jRBSuperior.setText("Superior");
        jRBSuperior.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRBSuperiorStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBMedio)
                    .addComponent(jRBSuperior))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRBMedio)
                .addGap(18, 18, 18)
                .addComponent(jRBSuperior)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 100));

        jLabel5.setText("Ano");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jCBSerie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "1º ano A", "1º ano B", "1º ano C", "1º ano D", "1º ano E", "1º ano F", "2º ano A", "2º ano B", "2º ano C", "2º ano D", "2º ano E", "2º ano F", "3º ano A", "3º ano B", "3º ano C", "3º ano D", "3º ano E", "3º ano F" }));
        jCBSerie.setEnabled(false);
        getContentPane().add(jCBSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 120, -1));

        jCBCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Sistemas de Informação", "Zootecnica" }));
        jCBCurso.setEnabled(false);
        jCBCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBCursoActionPerformed(evt);
            }
        });
        getContentPane().add(jCBCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 130, -1));

        jLabel6.setText("Curso");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        setSize(new java.awt.Dimension(425, 341));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        // TODO add your handling code here:
        if (!(jTFDisciplina.getText().isEmpty()) && !(jTFCargaHoraria.getText().isEmpty()) &&
           (jRBMedio.isSelected() || jRBSuperior.isSelected()) && (jCBProfessor.getSelectedItem() != "") &&
           ((jCBSemestre.getSelectedItem() != "Selecione..." ) || (jCBSerie.getSelectedItem() != "Selecione..." ))){
            
            this.infoJanela = new HashMap<>();
            
            this.infoJanela.put("Disciplina", jTFDisciplina.getText());
            
            infoJanela.put("Semestre", "");
            
            if (jRBMedio.isSelected()){
                infoJanela.put("Serie", String.valueOf(jCBSerie.getSelectedIndex()));
            }else if (jRBSuperior.isSelected()){
                infoJanela.put("Semestre", String.valueOf(jCBSemestre.getSelectedIndex()));
                infoJanela.put("Curso", String.valueOf(jCBCurso.getSelectedItem()));
            }
            
            infoJanela.put("Horario", jTFCargaHoraria.getText());
            infoJanela.put("Id_Professor", jTFCodigoProfessor.getText());
            
            ControlDisciplina cd = new ControlDisciplina();
            
            if (!jTFCodigo.getText().isEmpty()){
                this.infoJanela.put("Codigo", jTFCodigo.getText());
                
                if (cd.ControlAlterar(this.infoJanela)){
                    JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Não foi possível salvar as alterações!");
                }
            }else{
               if (cd.ControlInserir(this.infoJanela)) {
                    JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Não foi possível realizar o cadastro!");
                } 
            }
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios (em negrito)!");
        }
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jRBMedioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRBMedioStateChanged
        // TODO add your handling code here
        jCBSerie.setEnabled(jRBMedio.isSelected());
    }//GEN-LAST:event_jRBMedioStateChanged

    private void jRBSuperiorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRBSuperiorStateChanged
        // TODO add your handling code here:
        jCBSemestre.setEnabled(jRBSuperior.isSelected());
        jCBCurso.setEnabled(jRBSuperior.isSelected());
    }//GEN-LAST:event_jRBSuperiorStateChanged

    private void jCBProfessorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBProfessorItemStateChanged
        // TODO add your handling code here:
        for(String[] professor: this.professores){
            if (this.jCBProfessor.getSelectedItem().equals(professor[1])){
                this.jTFCodigoProfessor.setText(professor[0]);
            }
        }
    }//GEN-LAST:event_jCBProfessorItemStateChanged

    private void jCBCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanCad_Disciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanCad_Disciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanCad_Disciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanCad_Disciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanCad_Disciplina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JComboBox<String> jCBCurso;
    private javax.swing.JComboBox jCBProfessor;
    private javax.swing.JComboBox jCBSemestre;
    private javax.swing.JComboBox jCBSerie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRBMedio;
    private javax.swing.JRadioButton jRBSuperior;
    private javax.swing.JTextField jTFCargaHoraria;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFCodigoProfessor;
    private javax.swing.JTextField jTFDisciplina;
    private javax.swing.ButtonGroup nivelGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarJanela() {
        this.setVisible(true);
    }

    @Override
    public void setValoresSelecao(HashMap selecao) {
        jTFCodigo.setText(selecao.get("Codigo").toString());
        jTFDisciplina.setText(selecao.get("Disciplina").toString());
        jTFCargaHoraria.setText(selecao.get("Carga_Horaria").toString());
        jTFCodigoProfessor.setText(selecao.get("Codigo_Professor").toString());
        jCBProfessor.setSelectedItem(selecao.get("Nome_Professor").toString());
        
        jCBSemestre.setSelectedIndex((int) selecao.get("Semestre"));
        jCBSemestre.setEnabled(jCBSemestre.getSelectedIndex() > 0);
        jRBSuperior.setSelected(jCBSemestre.getSelectedIndex() > 0);
        jCBCurso.setEnabled(jCBSemestre.getSelectedIndex() > 0);
        jCBCurso.setSelectedItem(selecao.get("Curso").toString());
        
        jCBSerie.setSelectedIndex((int) selecao.get("Serie"));
        jCBSerie.setEnabled(jCBSerie.getSelectedIndex() > 0);
        jRBMedio.setSelected(jCBSerie.getSelectedIndex() > 0);
    }
    
    public void preencherListaProfessores(){
        this.professores = new ControlProfessor().pegarListaDeProfessores();
        
        for (String[]  professor: professores) {
            jCBProfessor.addItem(professor[1]);
        }
    }
    
}
