/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ControleDeFrequencia.View;

import br.com.ControleDeFrequencia.Control.ControlDisciplina;
import br.com.ControleDeFrequencia.Control.ControlCronograma;
import br.com.ControleDeFrequencia.Model.TableModelGeneric;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas Eduardo
 */
public class JanCad_Cronograma extends javax.swing.JDialog implements ADMJanelas{
    
    private ArrayList<String[]> disciplinas;
    private ArrayList<String[]> professores;
    private HashMap<String, String> infoJanela;
    private String sqlEquipamentos = "Select e.codigo, e.descricao from equipamento as e inner join aula_equipamento as ae "
            + "on e.codigo = ae.id_equipamento where"; 
    private TableModelGeneric tabelaModelo = null;
    private int codigoAula = 0;
    
    /**
     * Creates new form JanCad_Cronograma
     */
    public JanCad_Cronograma() {
        this.setModal(true);
        sqlEquipamentos = sqlEquipamentos + " id_aula = "+String.valueOf(this.codigoAula);
        initComponents();
        this.jLNumeroAula.setText(String.valueOf(this.codigoAula));
        //preencherListaProfessores();
        preencherListaDisciplinas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jCBDisciplina = new javax.swing.JComboBox<>();
        jTFDisciplinaCodigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanelOpcoes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFHorasDiarias = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter horas_d= new javax.swing.text.MaskFormatter("##");
            horas_d.setPlaceholderCharacter('_');
            jTFHorasDiarias = new javax.swing.JFormattedTextField(horas_d);
        }
        catch (Exception e){
        }
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFTFDataAula = new javax.swing.JFormattedTextField();
        jFTFHoraInicio = new javax.swing.JFormattedTextField();
        jFTFHoraTermino = new javax.swing.JFormattedTextField();
        jScrollPaneTable = new javax.swing.JScrollPane();
        try{
            this.tabelaModelo = new TableModelGeneric(this.sqlEquipamentos);
        } catch(SQLException e){
            e.printStackTrace();
        }
        jTableCronograma = new javax.swing.JTable(this.tabelaModelo);
        jLabel5 = new javax.swing.JLabel();
        jLNumeroAula = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBtnSalvar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Aula");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Disciplina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jCBDisciplina.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBDisciplinaItemStateChanged(evt);
            }
        });

        jTFDisciplinaCodigo.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFDisciplinaCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFDisciplinaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");

        jPanelOpcoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Data da Aula");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Horas Diárias");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Hora do ínicio");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Hora do termino");

        jFTFDataAula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        try{ 
            javax.swing.text.MaskFormatter data_aula= new javax.swing.text.MaskFormatter("##/##/####");
            data_aula.setPlaceholderCharacter('_');
            jFTFDataAula = new javax.swing.JFormattedTextField(data_aula);
        }
        catch (Exception e){
        }

        jFTFHoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        try{
            javax.swing.text.MaskFormatter horas= new javax.swing.text.MaskFormatter("##:##");
            horas.setPlaceholderCharacter('_');
            jFTFHoraInicio = new javax.swing.JFormattedTextField(horas);
        }
        catch (Exception e){
        }

        jFTFHoraTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        try{
            javax.swing.text.MaskFormatter horas= new javax.swing.text.MaskFormatter("##:##");
            horas.setPlaceholderCharacter('_');
            jFTFHoraTermino = new javax.swing.JFormattedTextField(horas);
        }
        catch (Exception e){
        }

        javax.swing.GroupLayout jPanelOpcoesLayout = new javax.swing.GroupLayout(jPanelOpcoes);
        jPanelOpcoes.setLayout(jPanelOpcoesLayout);
        jPanelOpcoesLayout.setHorizontalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpcoesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(61, 61, 61))
                    .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                        .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTFHorasDiarias, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFTFDataAula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFTFHoraInicio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFTFHoraTermino, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelOpcoesLayout.setVerticalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFTFDataAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFHorasDiarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFTFHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFTFHoraTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTableCronograma.setModel(this.tabelaModelo);
        jScrollPaneTable.setViewportView(jTableCronograma);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Número da Aula:");

        jLNumeroAula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNumeroAula.setForeground(new java.awt.Color(255, 0, 0));
        jLNumeroAula.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Equipamentos:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLNumeroAula)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLNumeroAula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jBtnSalvar.setText("Salvar");
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSalvar)
                    .addComponent(jButton3))
                .addGap(40, 40, 40))
        );

        setSize(new java.awt.Dimension(540, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCBDisciplinaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBDisciplinaItemStateChanged
        // TODO add your handling code here:
        for(String[] disciplina: this.disciplinas){
            if (this.jCBDisciplina.getSelectedItem().equals(disciplina[1])){
                this.jTFDisciplinaCodigo.setText(disciplina[0]);
            }
        }
    }//GEN-LAST:event_jCBDisciplinaItemStateChanged

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        // TODO add your handling code here:
        if (!this.jFTFDataAula.getText().isEmpty() && !this.jFTFHoraInicio.getText().isEmpty()
            && !this.jFTFHoraTermino.getText().isEmpty() && !this.jTFHorasDiarias.getText().isEmpty()){
            
            this.infoJanela = new HashMap<>();
            
            this.infoJanela.put("DataAula", this.jFTFDataAula.getText());
            this.infoJanela.put("HoraInicio", this.jFTFHoraInicio.getText());
            this.infoJanela.put("HoraTermino", this.jFTFHoraTermino.getText());
            this.infoJanela.put("HorasDiarias", this.jTFHorasDiarias.getText());
            this.infoJanela.put("CodigoDisciplina", this.jTFDisciplinaCodigo.getText());
            
            ControlCronograma cc = new ControlCronograma();
            
            if(Integer.parseInt(this.jLNumeroAula.getText()) > 0){
                this.infoJanela.put("Codigo", String.valueOf(this.codigoAula));
                
                if (cc.ControlAlterar(this.infoJanela)){
                    JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!");
                }else{
                    JOptionPane.showMessageDialog(null, "Não foi possível realizar a alteração!");
                }
            }else{
                if (cc.ControlInserir(this.infoJanela)){
                   JOptionPane.showMessageDialog(null, "Aula cadastrado com sucesso!"); 
                }else{
                    JOptionPane.showMessageDialog(null, "Não foi possível realizar o cadastro!");
                }   
            }
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios!");
        }
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCBDisciplina;
    private javax.swing.JFormattedTextField jFTFDataAula;
    private javax.swing.JFormattedTextField jFTFHoraInicio;
    private javax.swing.JFormattedTextField jFTFHoraTermino;
    private javax.swing.JLabel jLNumeroAula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelOpcoes;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JTextField jTFDisciplinaCodigo;
    private javax.swing.JTextField jTFHorasDiarias;
    private javax.swing.JTable jTableCronograma;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarJanela() {
        this.setVisible(true);
    }

    @Override
    public void setValoresSelecao(HashMap selecao) {
        jLNumeroAula.setText(selecao.get("codigo").toString());
        jTFHorasDiarias.setText(selecao.get("HorasDiarias").toString());
        jTFDisciplinaCodigo.setText(selecao.get("codigoDisciplina").toString());
        jCBDisciplina.setSelectedItem(selecao.get("nomeDisciplina").toString());
        
        try {
            SimpleDateFormat sdfData = new SimpleDateFormat("dd/MM/yyyy");
            Calendar DataAula = (Calendar) selecao.get("DataAula");
            jFTFDataAula.setText(sdfData.format(DataAula.getTime()));
            
            SimpleDateFormat sdfTempo = new SimpleDateFormat("HH:mm");
            Calendar HoraInicio = (Calendar) selecao.get("HoraInicio");
            Calendar HoraTermino = (Calendar) selecao.get("HoraTermino");
            
            jFTFHoraInicio.setText(sdfTempo.format(HoraInicio.getTime()));
            jFTFHoraTermino.setText(sdfTempo.format(HoraTermino.getTime()));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /*public void preencherListaProfessores(){
        this.professores = new ControlProfessor().pegarListaDeProfessores();
        
        for (String[]  professor: professores) {
            jCBProfessor.addItem(professor[1]);
        }
    }*/
    
    public void preencherListaDisciplinas(){
        this.disciplinas = new ControlDisciplina().pegarListaDeDisciplina();
        
        for (String[] disciplina: disciplinas){
            jCBDisciplina.addItem(disciplina[1]);
        }
    }
    
}
