/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ControleDeFrequencia.View;

import br.com.ControleDeFrequencia.Control.ControlTurma;
import java.util.HashMap;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author jerffeson
 */
public class JanCad_Turma  extends javax.swing.JDialog implements ADMJanelas{
    
    public HashMap infoJanela = null;
    /**
     * Creates new form JanCad_Turma
     */
    public JanCad_Turma() {
        this.setModal(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnSalvar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFAno_letivo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCBGraduacao = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTdescricao = new javax.swing.JTextArea();
        jBSalvar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();

        jBtnSalvar.setText("Salvar");
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Turma");
        setMinimumSize(new java.awt.Dimension(450, 320));

        jPanel1.setMinimumSize(new java.awt.Dimension(450, 320));
        jPanel1.setPreferredSize(new java.awt.Dimension(443, 431));

        jLabel1.setText("Ano Letivo");

        jTFAno_letivo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setText("Graduação");

        jCBGraduacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Superior", "Técnico" }));
        jCBGraduacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBGraduacaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Descrição");

        jTdescricao.setColumns(20);
        jTdescricao.setRows(5);
        jScrollPane1.setViewportView(jTdescricao);

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformjBtnSalvarActionPerformeded(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Código");

        jTCodigo.setEditable(false);
        jTCodigo.setToolTipText("");
        jTCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCodigo(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCBGraduacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFAno_letivo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBCancelar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBGraduacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFAno_letivo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBSalvar))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jBCancelar.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCBGraduacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBGraduacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBGraduacaoActionPerformed

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBSalvarActionPerformjBtnSalvarActionPerformeded(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformjBtnSalvarActionPerformeded
        // TODO add your handling code here:
        
        if (!(this.jTFAno_letivo.getText().isEmpty()) ) {

            this.infoJanela = new HashMap();
            
            this.infoJanela.put("ano_letivo", this.jTFAno_letivo.getText());
            this.infoJanela.put("descricao", this.jTdescricao.getText());
//            this.infoJanela.put("graduacao", this.jTFAno_letivo.getText());
            
            if ( this.jCBGraduacao.getSelectedItem().toString().equals("Superior") ){
                this.infoJanela.put("graduacao", "" + 1);
            }
            else{
                this.infoJanela.put("graduacao", "" + 2);
            }

            ControlTurma ct = new ControlTurma();
            
            if (!(this.jTCodigo.getText().isEmpty())){
                this.infoJanela.put("codigo", this.jTCodigo.getText());
                if (ct.ControlAlterar(this.infoJanela)){
                        JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!");
                    }else{
                        JOptionPane.showMessageDialog(null, "Não foi possivel salvar as alterações!");
                    }
            }else{
                if (ct.ControlInserir(infoJanela)) {
                    JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Não foi possivel realizar o cadastro!");
                }
            }
            
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios (em negrito)!");
        }
    }//GEN-LAST:event_jBSalvarActionPerformjBtnSalvarActionPerformeded

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTCodigo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCodigo
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCodigo


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JComboBox jCBGraduacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTFAno_letivo;
    private javax.swing.JTextArea jTdescricao;
    // End of variables declaration//GEN-END:variables


    @Override
    public void setValoresSelecao(HashMap selecao) {
        System.err.println(selecao.get("graduacao").toString());
        if (Integer.parseInt(selecao.get("graduacao").toString()) == 1){
            System.err.println("SUPERIOR");
            jCBGraduacao.setSelectedItem("Superior");
        }
        else {
            System.err.println("TEC");
            jCBGraduacao.setSelectedItem("Técnico");
        }
        jTdescricao.setText(selecao.get("descricao").toString());
        jTFAno_letivo.setText(selecao.get("ano_letivo").toString());
        jTCodigo.setText(selecao.get("codigo").toString());
    }                 

    @Override
    public void mostrarJanela() {
        this.setVisible(true);
    }
}
